### ISSUE TITLE
写法问题

### ISSUE THREAD

**Issue by wwhgtt** [1340641314/react-kelink#1]
发现在我的IDE里面很多报错信息，可以考虑加一个eslintrc文件，规范一下语法

**Comment by lzxb** [comment]
@wwhgtt 
我使用的是Brackets开发的，并没有使用IDE，主要是哪里报错比较多，能上传截图看看么

**Comment by lzxb** [comment]
@wwhgtt 已经提交了代码风格的问题，用vs code格式化和检测了一遍，登录模块还没完成，也提交上去了

**Comment by wwhgtt** [comment]
学习下
