### ISSUE TITLE
单页面应用和多页面应用

### ISSUE THREAD

**Issue by GZWZC** [1340641314/react-kelink#2]
你好，我是从这里进来这个项目的。
`http://react-china.org/t/react-redux-react-router/5767`

你这个项目是属于单页面应用吧，应该不属于多页面应用吧。
我有个项目外的问题想请教下，如果是多页面应用的话，能使用到reduce吗？

**Comment by lzxb** [comment]
肯定都可以，需要你自己权衡利弊
